config:
  switch: test  #环境开关 test \ pre \ prod 

envs:
  test:
    public:
      host: https://test-digital.hnlshm.com
      username: 18620130825
      password: 58jv49V9
      header:
        Content-Type: application/json
        x-app-id: store-selection-service
        X-App-Secret: c3RvcmUtc2VsZWN0aW9uLXNlcnZpY2U=

    franchiseDB:
      DB_host: rm-bp19895hqf6z7fr80.mysql.rds.aliyuncs.com
      DB_user: store_franchise_user
      DB_password: vUt4QcJm*@&e4MuB
      DB_port: 3306
      DataBase: store_franchise

    storeDB:
      DB_host: rm-bp19895hqf6z7fr80.mysql.rds.aliyuncs.com
      DB_user: store_core_user
      DB_password: vUt4QcJm*@&e4MuB
      DB_port: 3306
      DataBase: store_core

  prod:
    public:
      host: "https://test-digital.hnlshm.com"
      userName: 18620130825
      passWord: 58jv49V9

    franchiseDB:
      DB_host: rm-bp19895hqf6z7fr80.mysql.rds.aliyuncs.com
      DB_user: store_franchise_user
      DB_password: vUt4QcJm*@&e4MuB
      DB_port: 3306
      DataBase: store_franchise

    storeDB:
      DB_host: rm-bp19895hqf6z7fr80.mysql.rds.aliyuncs.com
      DB_user: store_core_user
      DB_password: vUt4QcJm*@&e4MuB
      DB_port: 3306
      DataBase: store_core